id = "zed-threefold"
name = "ThreeFold"
version = "0.0.1"
schema_version = 1
authors = ["Maxime Van Hees <vanheesm@threefold.tech>"]
description = "Install and manage your ThreeFold tools & resources"
repository = "https://github.com/maximevanhees/zed-threefold"
